pipeline {
    agent any

    tools{
        nodejs 'nodejs-20.6.1'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('Billage/Front/billage'){
                    sh '''
                    pwd
                    echo 'prepare'
                    echo 'npm install'
                    npm install
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Billage/Front/billage') {
                    sh '''
                    echo 'npm run build'
                    npm run build
                    '''
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('Billage/Front/billage'){
                    sh '''
                    echo 'Docker image build'
                    docker build -t docker-react-billage .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('Billage/Front/billage'){
                    sh '''
                    echo 'Deploy'                    

                    docker run -d -p 3000:80 --name billage-front docker-react:0.0.1
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }
    }
}