server:
  port: 8764

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://kb-discover-service:8764/eureka/
  server:
    renewalPercentThreshold: 0.7
