pipeline {
    agent any

    stages {
        stage('Springboot build') {
            steps {
                dir('IBK/Back/discovery-server'){
                    sh '''
                    pwd
                    echo 'springboot build'
                    cp -r /var/jenkins_home/backend-config/ibk/discovery-service/application.yml /var/jenkins_home/workspace/ibk_eureka_server/IBK/Back/discovery-service/src/main/resources/
                    chmod +x gradlew
                    ./gradlew clean build
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('IBK/Back/discovery-server'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-springboot-ibk-discovery-service:0.0.1 .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('IBK/Back/discovery-server'){
                    sh '''
                    echo 'Deploy'

                    docker run -d -p 8761:8761 --name ibk-discover-service docker-springboot-ibk-discovery-service:0.0.1
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }
    }
}