pipeline {
    agent any

    stages {
        stage('Springboot build') {
            steps {
                dir('Billage/Back/billage'){
                    sh '''
                    pwd
                    echo 'springboot build'
                    cp /var/jenkins_home/backend-config/billage/application.yml /var/jenkins_home/workspace/billage_back/Billage/Back/billage/src/main/resources/
                    chmod +x gradlew
                    ./gradlew clean build
                    gradle build -x test
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('Billage/Back/billage'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-springboot-billage:0.0.1 .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('Billage/Back/billage'){
                    sh '''
                    echo 'Deploy'

                    docker stop springboot
                    docker rm springboot

                    docker run -d -p 8080:8080 --name springboot docker-springboot-billage:0.0.1
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }
    }
}